apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-bharat
data:
  DBNAME: "emp46131559"
  DBUSER: "emp46131559"
  DBPASS: "password"
  DBHOST: "postgres"
  DBPORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-bharat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-bharat
  template:
    metadata:
      name: myapp-bharat
      labels:
        app: myapp-bharat
    spec:
      containers:
      - name: ovs
        image: bhvelaga/omtb 
        ports:
        - containerPort: 8093 
        envFrom:
          - configMapRef:
              name: app-config-bharat
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-bharat
spec:
  type: NodePort
  ports:
  - targetPort: 8093 
    port: 8093 
  selector:
    app: myapp-bharat
